stages:
    - deps
    - build
    - deploy

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/
        - dist/

build windows:
    stage: build
    tags:
        - windows
    script:
        - npm run install
        - npm run build
        - npm run dist
        
deploy windows:
    stage: deploy
    tags:
        - windows
    script:
        - echo "Deploying!"
        