before_script:
  - npm i -D

build windows:
    stage: build
    tags:
        - windows
    script:
        - npm run build
        - npm run dist
        
deploy windows:
    stage: deploy
    tags:
        - windows
    script:
        - echo "Deploying!"
        