stages:
    - bridge
    - build
    - deploy

# windows ntfs is REALLY slow
# dependencies:
#     stage: dependencies
#     tags:
#         - windows

#     cache:
#         paths:
#             - node_modules/

#     script:
#         - yarn install

#     only:
#         changes:
#             - yarn.lock

interface bridge:
    stage: bridge
    needs:
        pipeline: tivolicloud/interface

build launcher:
    stage: build
    tags:
        - windows

    environment:
        name: production-windows
    only:
        - pipelines

    # cache:
    #     policy: pull
    #     paths:
    #         - node_modules/

    variables:
        CSC_LINK: C:\Users\maki\tivoli-cloud-vr.p12
        #CSC_KEY_PASSWORD:

    script:
        # unzip artifact to .\interface
        - curl --output interface.zip %INTERFACE_ARTIFACT_URL%
        - Expand-Archive .\interface.zip .\interface-artifact
        - mv .\interface-artifact\interface\Release\ .\interface
        - Remove-Item -recurse -path .\interface-artifact
        - Remove-Item -recurse -path .\interface.zip

        # set version in package.json
        - echo %INTERFACE_VERSION%
        - ((Get-Content -path .\package.json -Raw) -replace
          "v0.0.0", $env:INTERFACE_VERSION) | Set-Content -Path .\package.json

        # install, build and package
        - yarn install
        - yarn run build
        - yarn run package

    artifacts:
        expire_in: 1 day
        paths:
            - dist/latest.yml
            - dist/Tivoli Cloud VR Setup.exe
            - dist/Tivoli Cloud VR Setup.exe.blockmap

deploy launcher:
    stage: deploy
    tags:
        - windows

    environment:
        name: production-windows
    only:
        - pipelines

    script:
        - cd gitlab/scripts
        - yarn install
        - yarn run deploy
