stages:
    - build
    - deploy

.production:
    only:
        - /^[0-9]+?\.[0-9]+?\.[0-9]+?$/i

.deploy:
    extends: .production
    when: manual
    allow_failure: false

launcher windows:
    stage: build
    tags:
        - windows

    extends: .production

    variables:
        CSC_LINK: C:\tivoli-cloud-vr.p12
        # CSC_KEY_PASSWORD

    script:
        - cd .gitlab
        - node update-version.js
        - cd ..

        - yarn install
        - yarn build
        - yarn package

    artifacts:
        expire_in: 1 day
        paths:
            - dist/*.exe
            - dist/*.blockmap
            - dist/*.yml

launcher linux:
    stage: build
    image: archlinux:latest

    extends: .production

    script:
        # nodejs-lts-fermium is 14
        - pacman -Syu --noconfirm nodejs-lts-fermium npm yarn python binutils git openssh

        - cd .gitlab
        - node update-version.js
        - cd ..

        - yarn install
        - yarn build
        - yarn package

    artifacts:
        expire_in: 1 day
        paths:
            - launcher/dist/*.AppImage
            - launcher/dist/*.pacman
            - launcher/dist/*.deb
            - launcher/dist/*.yml

upload launcher:
    stage: deploy
    image: google/cloud-sdk:alpine

    extends: .deploy

    needs:
        - job: launcher windows
          artifacts: true
        - job: launcher linux
          artifacts: true

    script:
        - gcloud auth activate-service-account --key-file $GCP_AUTH_JSON
        - gsutil cp
          "*.exe" "*.blockmap"
          "*.AppImage" "*.deb" "*.pacman"
          "*.yml"
          gs://tivolicloud-cdn/releases/launcher
