stages:
    #- bridge
    - build
    - deploy

# windows ntfs is REALLY slow
# dependencies:
#     stage: dependencies
#     tags:
#         - windows

#     cache:
#         paths:
#             - node_modules/

#     script:
#         - yarn install

#     only:
#         changes:
#             - yarn.lock

build launcher:
    stage: build
    tags:
        - windows

    environment:
        name: production-windows
    only:
        - pipelines

    # cache:
    #     policy: pull
    #     paths:
    #         - node_modules/

    variables:
        CSC_LINK: C:\Users\maki\tivoli-cloud-vr.p12
        # CSC_KEY_PASSWORD:
        # from pipeline, should have:
        #   RELEASE_NUMBER
        #   UPSTREAM_JOBS_URL
        #   UPSTREAM_JOB

    script:
        # prepare: download and unzip interface and change version in package.json
        - cd .gitlab
        - yarn install
        - yarn run prepare
        - cd ..

        # install, build and package
        - yarn install
        - yarn run build
        - yarn run package

    artifacts:
        expire_in: 1 day
        paths:
            - dist/latest.yml
            - dist/Tivoli Cloud VR Setup.exe
            - dist/Tivoli Cloud VR Setup.exe.blockmap

deploy launcher:
    stage: deploy
    tags:
        - windows

    dependencies:
        - build launcher

    environment:
        name: production-windows
    only:
        - pipelines

    script:
        - cd .gitlab
        - yarn install
        - yarn run deploy
