stages:
    - dependencies
    - build
    - deploy

# .production:
#     only:
#         - /^[0-9]+?\.[0-9]+?\.[0-9]+?$/i

.deploy:
    # extends: .production
    when: manual
    allow_failure: false

dependencies:
    stage: dependencies
    image: node:lts

    cache:
        key:
            files:
                - yarn.lock
        paths:
            - node_modules

    script:
        - yarn install
        - yarn ngcc --create-ivy-entry-points

launcher linux:
    stage: build
    image: node:lts

    # extends: .production

    cache:
        key:
            files:
                - yarn.lock
        paths:
            - node_modules
        policy: pull

    script:
        # - cd .gitlab
        # - node update-version.js
        # - cd ..

        - yarn install
        - yarn build
        - yarn package

    artifacts:
        expire_in: 1 day
        paths:
            - dist/*.AppImage
            - dist/*.yml

launcher windows:
    stage: build
    tags:
        - windows

    # extends: .production

    variables:
        CSC_LINK: C:\tivoli-cloud-vr.ci.pfx
        # CSC_KEY_PASSWORD

    script:
        # - cd .gitlab
        # - node update-version.js
        # - cd ..

        - yarn install
        - yarn build
        - yarn package

    artifacts:
        expire_in: 1 day
        paths:
            - dist/*.exe
            - dist/*.blockmap
            - dist/*.yml

upload launcher:
    stage: deploy
    image: google/cloud-sdk:alpine

    extends: .deploy

    needs:
        - job: launcher windows
          artifacts: true
        - job: launcher linux
          artifacts: true

    script:
        - gcloud auth activate-service-account --key-file $GCP_AUTH_JSON

        - cd dist
        - gsutil cp
          "*.exe" "*.blockmap"
          "*.AppImage"
          gs://tivolicloud-cdn/releases/launcher

        - gsutil cp
          "latest*.yml"
          gs://tivolicloud-cdn/releases/launcher
