stages:
    - deps
    - build
    - deploy

cache:
  paths:
    - node_modules/
    - dist/ 

deps windows:
    stage: deps
    tags:
        - windows
    script:
        - npm i -D

build windows:
    stage: build
    tags:
        - windows
    script:
        - npm run build
        - npm run dist
        
deploy windows:
    stage: deploy
    tags:
        - windows
    script:
        - echo "Deploying!"
        