stages:
    #- bridge
    - build
    - deploy

# windows ntfs is REALLY slow
# dependencies:
#     stage: dependencies
#     tags:
#         - windows

#     cache:
#         paths:
#             - node_modules/

#     script:
#         - yarn install

#     only:
#         changes:
#             - yarn.lock

build launcher:
    stage: build
    tags:
        - windows

    environment:
        name: production-windows
    only:
        - pipelines

    # cache:
    #     policy: pull
    #     paths:
    #         - node_modules/

    variables:
        CSC_LINK: C:\Users\maki\tivoli-cloud-vr.p12
        # CSC_KEY_PASSWORD:
        # from pipeline, should have:
        #   RELEASE_NUMBER
        #   UPSTREAM_PROJECT_URL
        #   UPSTREAM_BRANCH
        #   UPSTREAM_JOB

    script:
        # unzip artifact to interface/
        - Invoke-WebRequest
          -OutFile .\interface-artifact.zip
          -Uri $env:UPSTREAM_PROJECT_URL/-/jobs/artifacts/$env:UPSTREAM_BRANCH/download?job=$env:UPSTREAM_JOB
        - Expand-Archive .\interface-artifact.zip .\interface-artifact
        - mv .\interface-artifact\interface\Release\ .\interface
        - Remove-Item -recurse -path .\interface-artifact.zip
        - Remove-Item -recurse -path .\interface-artifact

        # set version in package.json
        - ((Get-Content -path .\package.json -Raw) -replace
          "v0.0.0", $env:RELEASE_NUMBER) | Set-Content -Path .\package.json

        # install, build and package
        - yarn install
        - yarn run build
        - yarn run package

    artifacts:
        expire_in: 1 day
        paths:
            - dist/latest.yml
            - dist/Tivoli Cloud VR Setup.exe
            - dist/Tivoli Cloud VR Setup.exe.blockmap

deploy launcher:
    stage: deploy
    tags:
        - windows

    environment:
        name: production-windows
    only:
        - pipelines

    script:
        - cd gitlab/scripts
        - yarn install
        - yarn run deploy
